require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/etl/migrate/*'
    - 'db/etl/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - './.simplecov'
    - 'client/node_modules/**/*'
    - 'app/mappers/zip_code_to_lat_lng_mapper.rb'
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.5
  UseCache: true

Bundler/OrderedGems:
  Enabled: true
  TreatCommentsAsGroupSeparators: false

Metrics/ModuleLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Description: 'Use consistent rescued exceptions variables naming.'
  Enabled: true
  PreferredName: error

Rails/Output:
  Exclude:
    - 'lib/**/*.rb'

Rails/UnknownEnv:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'
    - "spec/**/*"

Metrics/ClassLength:
  Max: 400

Metrics/AbcSize:
  Max: 30

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SignalException:
  EnforcedStyle: semantic

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
