require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/etl/migrate/*'
    - 'db/etl/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - './.simplecov'
    - 'client/node_modules/**/*'
    - 'app/mappers/zip_code_to_lat_lng_mapper.rb'
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.5
  UseCache: true

Bundler/OrderedGems:
  Enabled: true
  TreatCommentsAsGroupSeparators: false

Metrics/ModuleLength:
  CountComments: false
  Max: 100
  Description: Avoid modules longer than 100 lines of code.
  Enabled: true
  Exclude:
  - spec/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  CountComments: false
  Enabled: true
  Max: 25
  ExcludedMethods:
    - 'Struct.new'
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - '**/*.rake'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'
    - 'db/seeds.rb'
    - 'bin/setup'

Naming/RescuedExceptionsVariableName:
  Description: 'Use consistent rescued exceptions variables naming.'
  Enabled: true
  PreferredName: error

Rails/Output:
  Exclude:
    - 'lib/**/*.rb'

Rails/UnknownEnv:
  Enabled: false

Metrics/MethodLength:
  Max: 10
  Exclude:
    - 'db/migrate/*'
    - "spec/**/*"

Metrics/ClassLength:
  Max: 100

Metrics/AbcSize:
  Max: 15

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SignalException:
  EnforcedStyle: semantic

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
